apiVersion: v1
kind: Secret
metadata:
  name: {{ include "blog.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "blog.labels" . | nindent 4 }}
type: Opaque
data:
  db-password: {{ .Values.database.password | b64enc | quote }}
  db-user: {{ .Valuess.database.user | b64enc | quote }}
  api-secret: {{ .Values.api.secret | b64enc | quote }}
