apiVersion: v1
kind: Service
metadata:
  name: {{ include "blog.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "blog.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.api.port }}
      targetPort: blog
      protocol: TCP
      name: blog
  selector:
    {{- include "blog.selectorLabels" . | nindent 4 }}