---
name: Golang lint
on:
  push:
    paths:
      - "go.sum"
      - "go.mod"
      - "**.go"
      - ".github/workflows/golang_lint.yml"
      - ".golangci.yml"
  pull_request:

jobs: 
  golangci:
    permissions:
      contents: read
      pull-requests: read

    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      
      - name: Install Go
        uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5.0.0
        with:
          go-version: 1.22.x
      
      - name: Install dependencies
        run: |
          go mod tidy
          go mod vendor

      - name: Clear Go build cache
        run: go clean -cache -modcache -i -r

      - name: Build the project
        run: go build ./...
        
      - name: Lint
        uses: golangci/golangci-lint-action@3cfe3a4abbb849e10058ce4af15d205b6da42804 # v4.0.0
        with:
          version: v1.56.2